### ISSUE TITLE
Site is not rendering properly.

### ISSUE THREAD

**Issue by ankitrgadiya** [fossasia/pslab.fossasia.org#10]
I don't know what is wrong but it looks like site is completely broken.

**Comment by jigyasa-grover** [comment]
Works fine for me, post relevant screenshots and also specify the browser name & version being used.

**Comment by ankitrgadiya** [comment]
Its strange I cloned the repo and tested locally and I was working fine. I even tried on other computer the official link is not rendering. So, for testing I copied the code into a testing repo and its working fine too.
Official link 
![screenshot from 2016-12-12 12-07-00](https://cloud.githubusercontent.com/assets/18071765/21090131/8fdc5c44-c063-11e6-960c-66816c0b26bd.png)
Local version
![screenshot from 2016-12-12 12-07-13](https://cloud.githubusercontent.com/assets/18071765/21090142/9dc6b3ea-c063-11e6-9a3a-c66fb719b042.png)


Browser Firefox 50.0.2

With different computer, different version of Firefox 45.5.1
![screenshot from 2016-12-12 12-13-18](https://cloud.githubusercontent.com/assets/18071765/21090273/97addaaa-c064-11e6-9ce3-c70797467a42.png)

From my tablet Firefox
![tmp_2093-screenshot_2016-12-12-12-13-03474113527](https://cloud.githubusercontent.com/assets/18071765/21090330/072504bc-c065-11e6-913b-abb04d2cb143.png)

I used https://web-capture.net/ 
![shot-20161212-2837-1x74ubn 1](https://cloud.githubusercontent.com/assets/18071765/21090441/d134df66-c065-11e6-90e9-ef57e8256af5.jpeg)

**Comment by sanchittechnogeek** [comment]
i get this 

![screenshot 367](https://cloud.githubusercontent.com/assets/15964833/21091504/87690e3c-c06c-11e6-8445-c3df499d0f98.png)

**Comment by sanchittechnogeek** [comment]
@jig08 please check the screenshots

**Comment by mariobehling** [comment]
No clue, what was the error. It is fixed now though on the live site for me. Therefore closing it.

**Comment by ankitrgadiya** [comment]
@mariobehling Yeah its working properly now. CDN links fixed this problem. Go ahead close the issue
