### ISSUE TITLE
Improve message about device

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#124]
Can we have something along those lines somewhere on the top of the start page explaining what is PSLab:

PSLab is a hardware extension for your smartphone or PC. It enables you to measure all kinds of things by connecting it to your phone or PC via USB. You can use our Android or desktop app to collect and view the data. And, you can even plug in hundreds of compatible sensors to the PSLab pin slots. What experiments you can do is just limited to your imagination!

**Comment by cweitat** [comment]
Updated the text
