### ISSUE TITLE
Add more products to the shop

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#126]
More products to offer:
1. Buy one give one.
2. "Sell Android App" - Add a 5 Dollar App. Mention in the text "support the development of the app." Is there an option to send them a link to the installation on the Playstore automatically afterwards?
3. Change PSLab Edu Kit to "soon to come" or "Out of Stock" for now, but still list it.

**Comment by Juhi-Purswani** [comment]
Hello sir,
I wanted to contribute to your organization for gsco 2019. Please help me for getting started.
Thanks
