### ISSUE TITLE
Make 360 degree view of PSLab on the front page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#127]
How to make a 360 degree view that people can move around possible on the start page?

![screenshot from 2018-11-20 03-05-12](https://user-images.githubusercontent.com/1583873/48746799-3afe3d00-ec71-11e8-8909-5d4c0d0dc5af.png)

**Comment by subhahu123** [comment]
@mariobehling  Require 360 degree image file for this ?
