### ISSUE TITLE
Improve blog section and blogs

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#129]
In the blog section show full width of blogs and show full article.
![screenshot from 2018-11-20 03-13-03](https://user-images.githubusercontent.com/1583873/48747079-53bb2280-ec72-11e8-94e6-5cd9a4464a91.png)

**Comment by cweitat** [comment]
dont understand,

**Comment by mariobehling** [comment]
* Make the blog post full length at https://pslab.io/blog/
* Could we have the featured images back? Someone needs to compare the original blog and this one.
* Need to change all images which are loading from blog.fossasia.org to local images in the database (I already imported all of them)

**Comment by cweitat** [comment]
Featured images back
Managed to import images to local. but unable to import from page 7 onnwards
