### ISSUE TITLE
No Favicon

### ISSUE THREAD

**Issue by ankitrgadiya** [fossasia/pslab.fossasia.org#13]
I found out that there's no favicon.
So, I decided to fix it.

**Comment by ankitrgadiya** [comment]
I have three of them. 
I designed this 
![favicon](https://cloud.githubusercontent.com/assets/18071765/21152974/9b412228-c18e-11e6-81f3-b7d9dd946ebd.png)

Or we can use Fossasia "F" favicon as used in GCI site and most other fossasia sites.

![fossasia](https://cloud.githubusercontent.com/assets/18071765/21153049/e3620374-c18e-11e6-820a-48eaec26adb6.png)

Or we can use this Font Awesome svg
![flask](https://cloud.githubusercontent.com/assets/18071765/21153199/784f51a8-c18f-11e6-9c31-ac66a1ba9023.png)

**Comment by Princu7** [comment]
All of them look good. What do you guys think @jig08 @m1guelpf @hemantjadon @niccokunzmann Which one should we choose?

**Comment by m1guelpf** [comment]
@Princu7 I like the Font Awesome SVG

**Comment by Princu7** [comment]
@m1guelpf Yeah. I also like the design. Let's see what others think and pick one of them.

**Comment by hemantjadon** [comment]
Font awesome avg I guess for the favicon.

**Comment by ankitrgadiya** [comment]
Okay! Thanks for helping me select. I'm going to use Font Awesome svg (Flask). :-)

**Comment by ankitrgadiya** [comment]
Thanks guys for helping me choose one. So, can I use Font Awesome svg now?

**Comment by ankitrgadiya** [comment]
Okay Favicon added. Flask svg by Font Awesome
PR #15

**Comment by hemantjadon** [comment]
Nice work @ankitrgadiya

**Comment by ankitrgadiya** [comment]
Thanks!
