### ISSUE TITLE
Import images and link images in posts to own WP installation

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#130]
1. Imported blog posts still use the images on blog.fossasia.org. Instead they should be imported and linked / embedded from the installation itself.

2. Add featured images into the posts.

**Comment by cweitat** [comment]
Featured images back
Managed to import images to local. but unable to import from page 7 onnwards

**Comment by cweitat** [comment]
found root of problem. images must originally be https. http://fossasia.org will face errors in importing. Thus changing all links to https://fossasia,org before importing

**Comment by cweitat** [comment]
Finished
