### ISSUE TITLE
Add team section "Who is behind PSLab" with 3 or 4 columns

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#132]
Add section "Who is behind PSLab" with 3 or 4 columns below "specifications" and
* scroll over to show profile links
* title and if possible short text below

**Comment by cweitat** [comment]
so which profiles?

**Comment by mariobehling** [comment]
Please add as follows:
Mario, Padmal, Weitat,
Hong Phuc, Lorenz, 
Below "See More" and link to a new page "Team" and add all other members as either a) Developers, b) Advisers or c) Alumni (Former developers are Alumni)
