### ISSUE TITLE
Add section "What sensors are available for PSLab?"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#133]
Add a section about sensors on the start page and take it out on the "about" page. With the text:

* Pocket Science Lab can support a number of sensors and display the data in the app. Any sensor with the I2C standard can be plugged into the device using the digital pins. There are hundreds of compatible sensors available on the market. As a technically versatile user or developer you can also obtain data directly from the USB port or develop your own app. The data protocol uses the UART standard.

* Add a picture next or below with sensors

* Add a table with sensors their name and purpose below

**Comment by mariobehling** [comment]
Please also add a full list at https://pslab.io/sensors/ (which is linked from the data sheet as well).

**Comment by cweitat** [comment]
https://docs.google.com/spreadsheets/d/1f9cSvnRS_qqUORNXejuwGRm8rfJAa2xLt3UOWpH7pVg/edit#gid=0
