### ISSUE TITLE
Add an option "Donate PSLab for Education" to website

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#139]
People should be able to donate/buy PSLabs for education purposes. We need a write up of a short story why and how for that as well.

**Comment by Dharmesh-Poddar** [comment]
can I work on it ..

**Comment by cweitat** [comment]
@mariobehling to add details

**Comment by ayushiitr2901** [comment]
Hi, is this issue still open. If yes I would like to contribute to it. I am new working at FossAsia and this issue seems to be great start.
