### ISSUE TITLE
Site not rendering properly.

### ISSUE THREAD

**Issue by ankitrgadiya** [fossasia/pslab.fossasia.org#14]
I reported the same issue before #10  @BrainBuzzer fixed it with CDN links but the issue persist for Developers page.

![screenshot from 2016-12-13 22-56-24](https://cloud.githubusercontent.com/assets/18071765/21151135/670cf01a-c187-11e6-8d1a-f97022a4babb.png)

**Comment by BrainBuzzer** [comment]
I'm working on it

**Comment by BrainBuzzer** [comment]
I forgot to edit that one page. I thought all links are on same page .

**Comment by ankitrgadiya** [comment]
No worries I fixed it.

**Comment by abishekvashok** [comment]
Now we can close this then guys

**Comment by hemantjadon** [comment]
Seems like fixed. So closing this.
