### ISSUE TITLE
Change images and update active members list

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab.fossasia.org#140]
Following changes needs to be made on the website:

* Images of contributors - Harsh and Abhinav needs to be changed
* Harsh and Abhinav needs to be transfered from alumni list to active members list

**Comment by cweitat** [comment]
can I have the link of the images?

**Comment by cweitat** [comment]
shifted position. please give images soon. you can upload here as well

**Comment by cweitat** [comment]
@harsh-2711 @abhinavraj23

**Comment by cweitat** [comment]
description as well if you want to amend.

**Comment by cweitat** [comment]
@Avjeet pls post the description here as well
