### ISSUE TITLE
Alignment of Contact section links in the footer

### ISSUE THREAD

**Issue by roninx991** [fossasia/pslab.fossasia.org#142]
The contact us section links are not aligned properly due to fontawesome icons.

## Current Behaviour
![screenshot from 2018-12-18 15-10-55](https://user-images.githubusercontent.com/20491970/50146350-88ee7b00-02d9-11e9-8859-6e65c3bf8a91.png)

## Expected Behaviour
![screenshot from 2018-12-18 15-21-00](https://user-images.githubusercontent.com/20491970/50146404-a58ab300-02d9-11e9-84f5-095c82bbcf5b.png)

## Do you want to resolve this issue?
Yes, I would like to resolve this issue.

**Comment by mariobehling** [comment]
The live site is a Wordpress now. We are not using the site anymore. We only use the issue tracker to collect issues.
