### ISSUE TITLE
Update team members for GSoC 2019

### ISSUE THREAD

**Issue by cweitat** [fossasia/pslab.fossasia.org#150]
Attach description and image below

**Comment by Pipe-Runner** [comment]
humble_D is a Computer Science and Engineering graduate from Indian Institute of Technology ( Varanasi ), India. He is an application development and tinkering enthusiast who loves trying out new tech and coding patterns.

![photo6260425853880084818](https://user-images.githubusercontent.com/19551058/57773922-cc3d0080-7736-11e9-9fdf-2fefcf02e46a.jpg)

**Comment by CloudyPadmal** [comment]
Let's go with this for Padmal:::

> Padmal is an Electronic and Telecommunication Engineering graduate with a first class from University of Moratuwa, Sri Lanka. Being a past GSoC student building up the PSLab project with FOSSASIA, his interests lies in hardware/firmware development. This year he is mentoring both PSLab and NeuroLab projects..

![IMG](https://avatars2.githubusercontent.com/u/14261304?s=460&v=4)
