### ISSUE TITLE
Website is not rendering completely in Safari 

### ISSUE THREAD

**Issue by kushthedude** [fossasia/pslab.fossasia.org#158]
None of the hyperlinks and images are getting rendered in the Safari for pslab.io 

#### Screenshots:

<img width="856" alt="Screenshot 2020-01-31 at 6 29 01 AM" src="https://user-images.githubusercontent.com/44091822/73503711-05b3ba00-43f3-11ea-9609-fdeea1237629.png">

<img width="720" alt="Screenshot 2020-01-31 at 6 29 18 AM" src="https://user-images.githubusercontent.com/44091822/73503717-06e4e700-43f3-11ea-8699-2b7c9c806ab2.png">

**Comment by kushthedude** [comment]
cc: @CloudyPadmal @mariobehling

**Comment by mickeyrk** [comment]
I would like to work on this issue

**Comment by CloudyPadmal** [comment]
@mickeyrk is this issue still exist?

**Comment by kushthedude** [comment]
No
