### ISSUE TITLE
The site nav-bar is towards the right side

### ISSUE THREAD

**Issue by sudo-panda** [fossasia/pslab.fossasia.org#16]
Also the nav-bar doesn't move when we scroll down.

**Comment by sudo-panda** [comment]
I would like to fix this.

**Comment by hemantjadon** [comment]
@Baidya99 Sure go ahead. But after completetion do provide the before and after screenshots.

**Comment by sudo-panda** [comment]
I do not understand why there are so many classes in the css(or rather .less) with navbar in them
