### ISSUE TITLE
Button hover effect enhancement

### ISSUE THREAD

**Issue by nlok5923** [fossasia/pslab.fossasia.org#160]
I had observed some of the buttons on hover shows a change in color but not all.
example:
![Screenshot (798)](https://user-images.githubusercontent.com/56120084/81322274-97f9d880-9048-11ea-8ab4-8409308639f5.png)
![Screenshot (796)](https://user-images.githubusercontent.com/56120084/81322290-9cbe8c80-9048-11ea-9e9e-299041173bb6.png)

More Team Members on hover changes color
but not BUY PSlab Now button

Uniformity among all buttons would be better that's why 
I would like to work on this issue
please let me know.

**Comment by blackhat7355** [comment]
I would like to work on this issue.
Please let me know if I can do so.

**Comment by amandugar** [comment]
I would like to work on this issue
Please Let me know if I can help you

**Comment by aayushpatniya** [comment]
I would like to work on this issue.

**Comment by anandgupta887** [comment]
I would like to work on this issue

**Comment by anandgupta887** [comment]
Can I get the link of the page where the issue is?

**Comment by nlok5923** [comment]
Note that this is the feature request it need member review

**Comment by atulgawhane** [comment]
i want to work on this issue

**Comment by ghost** [comment]
Please allow me to work on this issue

**Comment by Ajil5467** [comment]
I would like to work on this issue

**Comment by akhil27styles** [comment]
Want to see the best hover effect? So please allow me to work on this issue

**Comment by mariobehling** [comment]
not needed.
