### ISSUE TITLE
website for FOSSASIA Science Lab

### ISSUE THREAD

**Issue by wavicles** [fossasia/pslab.fossasia.org#2]
Hi Mario 
Let us have a website for FOSSASIA Science Lab. This will be a common website for the tools we are supporting/developing, like ExpEYES, PSLab, Microhope etc... We will also keep adding the programs we conduct, the study material we develop on this site.  

Please register a new domain name like fossasiasciencelab.org    or sub-domain sciencelab.fossasia.org. Which one do you think is suitable?

I will create the html pages and will involve others too.
Thanks and regards

**Comment by mariobehling** [comment]
Good idea, maybe science.fossasia.org is good as it is shorter. Let's think about it step by step and let's collect content before we are making more unused subdomains (like PSlab which does not have content here). 

Can we start by collecting more stuff on the blog and then take the best content to build this new site? A new subdomain will not get as many hits as blog entries and if your main goal is to reach lots of people, you will achieve this on the blog.

Also we do not have an official link to ExpEYES and Microhope, but supported it through you of course. As we have lots of projects now, we need to focus on projects mainly or officially establish links with others.

Hong Phuc will bring a sensebox (https://www.sensebox.de) to the Science Hack event. Would be great to produce something like that in India and get more software tools going.

**Comment by nadia39** [comment]
I would like to contribute to this project.
I am a university student and I must take part in a Open Source Project for a class.
I can help with the design of the website.
Thank you.

**Comment by mariobehling** [comment]
Hi @nadia39 thanks for your interest. Currently, we are not completely clear about the content of the website. Therefore, this issue will be delayed. 

Please help with one of our other projects e.g. we need help with https://github.com/fossasia/loklak_search which is using Angular2.
