### ISSUE TITLE
Padding on mobile

### ISSUE THREAD

**Issue by dewanshrawat15** [fossasia/pslab.fossasia.org#21]
I'd like to beautify the page by simple giving some text padding and would also like to work on the response of the page. 😀

**Comment by hemantjadon** [comment]
Sure @dewanshrawat15 Go ahead :)

**Comment by bikrambhattacharya** [comment]
Is this issue still available? @hemantjadon

**Comment by abhi40308** [comment]
Sending patch for the same.
