### ISSUE TITLE
Keep top menu bar visible

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#24]
The top bar disappears when scrolling down. Keep it visible.

**Comment by alejoheredia** [comment]
@mariobehling Can I work on this? 😄

**Comment by mariobehling** [comment]
Please ensure top bar is semi-transparent as soon as scrolling down - also on red top area.

**Comment by alejoheredia** [comment]
@mariobehling But, It is already semi-transparent

**Comment by mariobehling** [comment]
Please compare on the FOSSASIA main site. As soon as you start scrolling down the transparency of the top bar changes. On the PSlab site the menu bar always appears completely transparent for me on Chrome.

![screenshot from 2016-12-23 18-09-02](https://cloud.githubusercontent.com/assets/1583873/21458978/532e3be2-c96d-11e6-8959-9ab90ef4048b.png)

**Comment by mariobehling** [comment]
Ah ok. I see it is changing as soon as the white area is appearing. Could you adopt it, so the top bar changes when the scrolling starts, please?

**Comment by abishekvashok** [comment]
@mariobehling I would like to work on the same pls
