### ISSUE TITLE
Add labs dropdown menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#25]
Add dropdown menu like in FOSSASIA sites

![screenshot from 2016-12-19 12-46-27](https://cloud.githubusercontent.com/assets/1583873/21302468/ae12b5ec-c5e9-11e6-9bb9-08e503eb54ea.png)

**Comment by idealadarsh** [comment]
@mariobehling Which links should be added in the dropdown menu?
And is the name of dropdown menu should be "Labs"?

**Comment by mariobehling** [comment]
See screenshot - Labs

Same links as on fossasia.org

**Comment by idealadarsh** [comment]
Moved Fossasia link into Labs dropdown. There was not much space left, the menu occupied two lines then.

**Comment by mariobehling** [comment]
> Moved Fossasia link into Labs dropdown. There was not much space left, the menu occupied two lines then.

Please do not do this. I am following up in a separate issue about the top bar sorting.

**Comment by mariobehling** [comment]
Follow up issue here https://github.com/fossasia/pslab.fossasia.org/issues/29
