### ISSUE TITLE
Avoid scroll bar in menu dropdown in small resolutions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#26]
![screenshot from 2016-12-19 12-48-25](https://cloud.githubusercontent.com/assets/1583873/21302470/b773e746-c5e9-11e6-9819-057f2dc6299c.png)

**Comment by alejoheredia** [comment]
@mariobehling I think that you can close this issue, because in the commit #27 I solved this too 😃
