### ISSUE TITLE
Sorting the top menu bar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#29]
Please implement the top bar as follows:

* [x] Add FOSSASIA logo on top left and link it to http://fossasia.org
* [x] Home linking to PSLab start page
* [x] Implement "Features" as top menu item
* [x] Implement "Getting Started" with sub items in the following order:
    * [x] Design your own experiments
    * [x] Installation
    * [x] Hardware Communication
* [x] Developers and Mentors
* [x] PSLabs Schematics
* [x] "Blog" linking to http://blog.fossasia.org/tag/pslab/

Please also ensure the top bar is implemented in the same way on http://pslab.fossasia.org/developers.html

**Comment by alejoheredia** [comment]
@mariobehling Does it have to be floating on the right?

**Comment by mariobehling** [comment]
@Heredroky Thanks. Please ensure the dropdown menu expands on scroll over. Cheers.

**Comment by hemanthsavasere** [comment]
Hi @mariobehling 
I want to work on this.
