### ISSUE TITLE
Invisible Text under navbar

### ISSUE THREAD

**Issue by AKostiv8** [fossasia/pslab.fossasia.org#38]
When you are scrolling down the text mixed and become invisible. Take a look a screenshot below:

![85](https://cloud.githubusercontent.com/assets/24627005/21463846/1d2aac5a-c978-11e6-8533-f1d8f1253c58.png)

**Comment by jigyasa-grover** [comment]
@AKostiv8  nice, would you like to take it up ?

**Comment by hemanthsavasere** [comment]
Hi @jig08 
I would like to work on this issue.
Thanks,

**Comment by AKostiv8** [comment]
@jig08  I have fixed it yesterday but my PR closed((( https://github.com/fossasia/pslab.fossasia.org/pull/40

**Comment by AKostiv8** [comment]
@jig08  and I also fixed next issues

**Comment by AKostiv8** [comment]
@jig08 this the live link of my changes https://akostiv8.github.io/pslab.fossasia.org/

**Comment by abishekvashok** [comment]
@jig08 consider closing it won't you, it's fixed :)
