### ISSUE TITLE
Footer symbol

### ISSUE THREAD

**Issue by AKostiv8** [fossasia/pslab.fossasia.org#39]
In the footer section doesn't use (where email address) standard Unicode and also the design is not so user-friendly.
 
![87](https://cloud.githubusercontent.com/assets/24627005/21463871/bef21140-c978-11e6-98ea-04455df152a1.png)

**Comment by ashwini0529** [comment]
I can take this up.

**Comment by Elgayar** [comment]
Before: 
![image](https://cloud.githubusercontent.com/assets/6567844/21508869/d7ea584e-cc8c-11e6-8b54-a53f4164cf49.png)

After:
![image](https://cloud.githubusercontent.com/assets/6567844/21508877/ece02e54-cc8c-11e6-8a41-e8ae612901fe.png)

@mariobehling

**Comment by mariobehling** [comment]
Thanks. Please change "About PSLab" to "Contact".

**Comment by Elgayar** [comment]
Okay, one second!

**Comment by Elgayar** [comment]
Done. @mariobehling

**Comment by abishekvashok** [comment]
@mariobehling mind closing it
