### ISSUE TITLE
Ensure all links act in same way and use same colors

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#45]
Currently links across the page behave differently, e.g. some have underlind on scroll over, some change color. Please implement as follows:

* [ ] Implement css for links and change html implementation of links to use CSS
* [ ] All links should use the same red color
* [ ] On scroll over underline links

**Comment by hemanthsavasere** [comment]
Hi @mariobehling 
I want to fix it and I am working on it.

**Comment by hemanthsavasere** [comment]
Hi @hemantjadon and @mariobehling 
the custom.css file's styles are applying to some, but I cannot override other links whose properties already has been defined in css/clean-blog.min.css  for that particular element.

**Comment by abishekvashok** [comment]
@hemanthsavasere use `!important` css attribute pls.

**Comment by abishekvashok** [comment]
@mariobehling since inactivity i thought I would deliver in a PR for the same #58

**Comment by Aakash-DD** [comment]
Is this issue still there, i want to work on this..

**Comment by sarnava1** [comment]
@mariobehling @abishekvashok @fossasia/pslab-admins @hemantjadon   is this still available? Please assign me this issue if it still exists.
