### ISSUE TITLE
Improve top menu bar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#46]
Improve the menu bar as follows:

* [ ] On scroll over make menu item bold
* [x] Decrease transparency in front of areas
* [x] On the main content area the menu is white and on scroll over links are blue. Implement as follows: Top menu items stay black and get bold
![screenshot from 2016-12-25 14-10-06](https://cloud.githubusercontent.com/assets/1583873/21471266/eeb16884-caab-11e6-8e94-31756d1fcf05.png)

**Comment by oanarosca** [comment]
May I fix the others? Also, I noticed that the developers' names are not centered, and I'd like to solve that too.

**Comment by mariobehling** [comment]
Please also make the menu items bold on scroll over in front of the red top area (instead of light grey).

**Comment by kmehant** [comment]
@mariobehling Can I work on this?

**Comment by abishekvashok** [comment]
@mariobehling should we do it (I mean to make them bold) as the fossasia.org website lacks that feature

**Comment by mariobehling** [comment]
Yes, please do. I think this site would benefit and we are not building an exact clone of the main fossasia site here. Cheers.

**Comment by idealadarsh** [comment]
@mariobehling Sir, please check the pull request.

**Comment by bikrambhattacharya** [comment]
Is this issue still available? @mariobehling

**Comment by Remorax** [comment]
@mariobehling Has this issue been resolved, or is something left? I would like to finish it if its' left.

**Comment by pranav1698** [comment]
Hey @mariobehling, 
Has everything been solved related to this issue(making the menu bar items bold) I want to work on that if it is still not resolved!!
I think it is not resolved as:
before bold property
![screenshot from 2018-09-21 17-31-38](https://user-images.githubusercontent.com/34754265/45880028-3d086480-bdc4-11e8-8522-cbb18ccac30b.png)
after bold property added
![screenshot from 2018-09-21 17-32-21](https://user-images.githubusercontent.com/34754265/45880064-5dd0ba00-bdc4-11e8-9300-430ce4b9d2fb.png)
