### ISSUE TITLE
After starting to scroll top bar menu items slightly move when changing color

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#59]
Expected behavior when user moves the page the color of the scroll bar should change, but menu items should not move.

**Comment by Rishabh-Kumar-Bothra** [comment]
sir, i am interested in this issue may i try to solve this?
thank you

**Comment by mittalprince** [comment]
Sir is this has been solved or not?
If not I want to work on it .
thank you

**Comment by CloudyPadmal** [comment]
Hi @mittalprince ! This issue is solved in #66 ! :) You can give a try to fix the other issues!!

**Comment by mittalprince** [comment]
k sir @CloudyPadmal 
thanks

**Comment by Rishabh-Kumar-Bothra** [comment]
@CloudyPadmal sir i think this is working perfect now.

**Comment by CloudyPadmal** [comment]
@adsk261095 will work on this issue

**Comment by adsk261095** [comment]
@CloudyPadmal  have u gone through the PR?
