### ISSUE TITLE
Add a page "Privacy" and provide a link on the footer

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#64]
We need a page for a privacy policy. Implement a simple site using the same style. Please do the following:
* Add link "Privacy" in the footer on the left hand side
* Implement the following order:  PSLab | FOSSASIA | Privacy
* Also Link "FOSSASIA" to http://fossasia.org

**Comment by viveksb007** [comment]
@mariobehling @iamareebjamal should i add [privacy_policy.html](https://github.com/fossasia/pslab-android/blob/development/docs/privacy_policy.html) in this repo and link it or link directly from pslab-android repo?
