### ISSUE TITLE
Width and top bar erroneous after color bulk update

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#9]
I bulk updated the color and on the local installation it all looks good.

However top bar and width are distorted on live site.

![screenshot from 2016-11-11 18 22 55](https://cloud.githubusercontent.com/assets/1583873/20211996/e45c3fe0-a83b-11e6-957d-ea3b37a765a0.png)

**Comment by Achint08** [comment]
![screen shot 2016-11-12 at 6 30 08 pm](https://cloud.githubusercontent.com/assets/15813932/20237948/2622fb1a-a906-11e6-936e-ef5a7cebddaf.png)

Hello, As we can see on the screenshot, Status :404 Not found for some of the files , specifically the vendor files. I hope this helps.

**Comment by mariobehling** [comment]
The files are there and were not changed. Not sure, where is the error. Please help and make a PR to fix it.  Cheers.

**Comment by Achint08** [comment]
On my local machine it is working fine but I think that live site is not updated because "http://pslab.fossasia.org/vendor/bootstrap/css/bootstrap.min.css" shows that "The site configured at this address does not contain the requested file. " and it shows "Jquery is not defined" .Kindly check it once more if the files are updated. If that doesn't solve the issue what about using CDN's?

**Comment by mariobehling** [comment]
@Achint08 I am still unclear, what is the cause of this issue. I think the CDN should have been updated by now. Below a screenshot of the issue. Let's see if anyone would like to take it on and dive in deeper.

![screenshot from 2016-12-11 19-17-32](https://cloud.githubusercontent.com/assets/1583873/21080021/bf61e16a-bfd6-11e6-93ab-104697946311.png)

**Comment by Achint08** [comment]
@mariobehling Is the website extracting data directly from this repository? In that case, There were bugs like there was no ending </div> tag at the end of the index.html. Problem can also be on server side also. Try to push again the files on the server. There have been people who have gone through these issues  . Let's Commit Something and push the branch gh-pages and it might solve the issue. New commits force jekyll to rebuild your pages. I can't see a issue on our side. If that doesn't work also , I am making a pull request which is using CDN for bootstrap , font-awesome and jquery. Merge it if nothing works. But most probably , issue is on server side as I have gone through.
